import type { Property, Agent, Testimonial } from './types';

export const agents: Agent[] = [
  {
    id: 'agent-1',
    name: 'Mag. Stefan Huber',
    agency: 'Alpen Immobilien Innsbruck',
    phone: '+43 512 123 456',
    email: 'huber@alpen-immobilien.at',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=80&h=80&fit=crop&crop=face',
    region: 'Tirol, Österreich',
    languages: ['Deutsch', 'Englisch', 'Italienisch'],
    propertiesCount: 28,
    rating: 4.9,
    reviewCount: 47,
  },
  {
    id: 'agent-2',
    name: 'Katharina Berger',
    agency: 'Premium Properties Vienna',
    phone: '+43 1 234 567',
    email: 'berger@premium-properties.at',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=80&h=80&fit=crop&crop=face',
    region: 'Wien, Österreich',
    languages: ['Deutsch', 'Englisch', 'Französisch'],
    propertiesCount: 41,
    rating: 4.8,
    reviewCount: 63,
  },
  {
    id: 'agent-3',
    name: 'Thomas Müller',
    agency: 'Münchner Immobilien GmbH',
    phone: '+49 89 123 4567',
    email: 'mueller@muenchner-immo.de',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop&crop=face',
    region: 'Bayern, Deutschland',
    languages: ['Deutsch', 'Englisch'],
    propertiesCount: 35,
    rating: 4.7,
    reviewCount: 52,
  },
  {
    id: 'agent-4',
    name: 'Sophie Zimmermann',
    agency: 'Swiss Premium Realty',
    phone: '+41 44 123 45 67',
    email: 'zimmermann@swiss-premium.ch',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=80&h=80&fit=crop&crop=face',
    region: 'Zürich, Schweiz',
    languages: ['Deutsch', 'Englisch', 'Französisch'],
    propertiesCount: 22,
    rating: 5.0,
    reviewCount: 31,
  },
];

// Using free 360° panorama images for demo VR tours
const PANORAMA_URLS = {
  livingroom: 'https://photo-sphere-viewer-data.netlify.app/assets/sphere.jpg',
  bedroom: 'https://photo-sphere-viewer-data.netlify.app/assets/sphere-small.jpg',
  kitchen: 'https://photo-sphere-viewer-data.netlify.app/assets/sphere.jpg',
  exterior: 'https://photo-sphere-viewer-data.netlify.app/assets/sphere-small.jpg',
};

export const properties: Property[] = [
  {
    id: 'prop-1',
    title: 'Luxuriöses Penthouse mit Bergpanorama',
    titleDe: 'Luxuriöses Penthouse mit Bergpanorama',
    description: 'Breathtaking penthouse apartment in the heart of Innsbruck with stunning panoramic views of the Nordkette mountain range. Floor-to-ceiling windows, state-of-the-art kitchen, and a wraparound terrace.',
    descriptionDe: 'Atemberaubendes Penthouse im Herzen Innsbrucks mit grandiosem Panoramablick auf die Nordkette. Raumhohe Fenster, hochmoderne Küche und eine umlaufende Dachterrasse. Luxuriöse Ausstattung auf höchstem Niveau.',
    type: 'penthouse',
    listingType: 'sale',
    price: 1_850_000,
    currency: 'EUR',
    pricePerSqm: 12_333,
    address: {
      street: 'Innstraße 45',
      city: 'Innsbruck',
      region: 'Tirol',
      country: 'AT',
      postalCode: '6020',
      lat: 47.2692,
      lng: 11.4041,
    },
    features: {
      rooms: 5,
      bedrooms: 3,
      bathrooms: 2,
      area: 150,
      floor: 8,
      totalFloors: 8,
      yearBuilt: 2021,
      parking: true,
      elevator: true,
      balcony: true,
      garden: false,
      cellar: true,
      energyClass: 'A+',
    },
    amenities: ['Concierge', 'Tiefgarage', 'Smart Home', 'Sauna', 'Fitnessraum', 'Dachterrasse'],
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&h=500&fit=crop',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=500&fit=crop',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=500&fit=crop',
    ],
    vrTours: [
      {
        id: 'vr-1-1',
        panoramaUrl: PANORAMA_URLS.livingroom,
        thumbnailUrl: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=120&h=80&fit=crop',
        roomName: 'Living Room',
        roomNameDe: 'Wohnzimmer',
      },
      {
        id: 'vr-1-2',
        panoramaUrl: PANORAMA_URLS.bedroom,
        thumbnailUrl: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=120&h=80&fit=crop',
        roomName: 'Master Bedroom',
        roomNameDe: 'Schlafzimmer',
      },
    ],
    agent: agents[0],
    status: 'active',
    createdAt: '2025-01-15',
    updatedAt: '2025-02-01',
    views: 1243,
    vrViews: 891,
    featured: true,
  },
  {
    id: 'prop-2',
    title: 'Traditionelles Chalet in Kitzbühel',
    titleDe: 'Traditionelles Chalet in Kitzbühel',
    description: 'Authentic Austrian chalet in the exclusive Kitzbühel ski resort. Panoramic mountain views, ski-in/ski-out access, and traditional alpine architecture with modern comforts.',
    descriptionDe: 'Authentisches österreichisches Chalet im exklusiven Skigebiet Kitzbühel. Panoramablick auf die Berge, Ski-in/Ski-out, traditionelle Tiroler Architektur mit modernem Komfort.',
    type: 'chalet',
    listingType: 'sale',
    price: 2_400_000,
    currency: 'EUR',
    pricePerSqm: 10_000,
    address: {
      street: 'Hinterstadt 12',
      city: 'Kitzbühel',
      region: 'Tirol',
      country: 'AT',
      postalCode: '6370',
      lat: 47.4467,
      lng: 12.3929,
    },
    features: {
      rooms: 7,
      bedrooms: 4,
      bathrooms: 3,
      area: 240,
      plotArea: 800,
      yearBuilt: 2019,
      parking: true,
      elevator: false,
      balcony: true,
      garden: true,
      cellar: true,
      energyClass: 'A',
    },
    amenities: ['Kamin', 'Sauna', 'Weinkeller', 'Ski-Raum', 'Außenpool', 'Heizung Holz'],
    images: [
      'https://images.unsplash.com/photo-1590073844006-33379778ae09?w=800&h=500&fit=crop',
      'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800&h=500&fit=crop',
      'https://images.unsplash.com/photo-1601918774516-5f28e4a7a3c3?w=800&h=500&fit=crop',
    ],
    vrTours: [
      {
        id: 'vr-2-1',
        panoramaUrl: PANORAMA_URLS.livingroom,
        thumbnailUrl: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=120&h=80&fit=crop',
        roomName: 'Living Room',
        roomNameDe: 'Stube',
      },
      {
        id: 'vr-2-2',
        panoramaUrl: PANORAMA_URLS.bedroom,
        thumbnailUrl: 'https://images.unsplash.com/photo-1601918774516-5f28e4a7a3c3?w=120&h=80&fit=crop',
        roomName: 'Master Suite',
        roomNameDe: 'Hauptschlafzimmer',
      },
      {
        id: 'vr-2-3',
        panoramaUrl: PANORAMA_URLS.exterior,
        thumbnailUrl: 'https://images.unsplash.com/photo-1590073844006-33379778ae09?w=120&h=80&fit=crop',
        roomName: 'Exterior',
        roomNameDe: 'Außenbereich',
      },
    ],
    agent: agents[0],
    status: 'active',
    createdAt: '2025-01-20',
    updatedAt: '2025-01-28',
    views: 2100,
    vrViews: 1567,
    featured: true,
  },
  {
    id: 'prop-3',
    title: 'Modernes Apartment im 1. Bezirk Wien',
    titleDe: 'Modernes Apartment im 1. Bezirk Wien',
    description: 'Elegant modern apartment in the heart of Vienna\'s historic 1st district. High ceilings, parquet flooring, and views of the Stephansdom. Walking distance to the opera and museums.',
    descriptionDe: 'Elegantes, modernes Apartment im historischen 1. Bezirk Wiens. Hohe Decken, Parkettboden und Blick auf den Stephansdom. Fußläufig zu Oper und Museen.',
    type: 'apartment',
    listingType: 'sale',
    price: 890_000,
    currency: 'EUR',
    pricePerSqm: 14_833,
    address: {
      street: 'Graben 17',
      city: 'Wien',
      region: 'Wien',
      country: 'AT',
      postalCode: '1010',
      lat: 48.2082,
      lng: 16.3738,
    },
    features: {
      rooms: 3,
      bedrooms: 2,
      bathrooms: 1,
      area: 60,
      floor: 4,
      totalFloors: 6,
      yearBuilt: 2018,
      parking: false,
      elevator: true,
      balcony: false,
      garden: false,
      cellar: true,
      energyClass: 'B',
    },
    amenities: ['Concierge', 'Klimaanlage', 'Fußbodenheizung', 'Videosprechanlage'],
    images: [
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=500&fit=crop',
      'https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=800&h=500&fit=crop',
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&h=500&fit=crop',
    ],
    vrTours: [
      {
        id: 'vr-3-1',
        panoramaUrl: PANORAMA_URLS.livingroom,
        thumbnailUrl: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=120&h=80&fit=crop',
        roomName: 'Living Room',
        roomNameDe: 'Wohnzimmer',
      },
    ],
    agent: agents[1],
    status: 'active',
    createdAt: '2025-02-01',
    updatedAt: '2025-02-10',
    views: 845,
    vrViews: 623,
    featured: false,
  },
  {
    id: 'prop-4',
    title: 'Luxusvilla am Zürichsee',
    titleDe: 'Luxusvilla am Zürichsee',
    description: 'Exceptional luxury villa on the shores of Lake Zurich with a private boat dock. Designed by award-winning architects, featuring an infinity pool, smart home technology and direct lake access.',
    descriptionDe: 'Außergewöhnliche Luxusvilla am Ufer des Zürichsees mit privatem Bootssteg. Von preisgekrönten Architekten entworfen – Infinitypool, Smart-Home-Technologie und direkter Seezugang.',
    type: 'villa',
    listingType: 'sale',
    price: 4_800_000,
    currency: 'CHF',
    pricePerSqm: 16_000,
    address: {
      street: 'Seestrasse 88',
      city: 'Küsnacht',
      region: 'Zürich',
      country: 'CH',
      postalCode: '8700',
      lat: 47.3232,
      lng: 8.5881,
    },
    features: {
      rooms: 9,
      bedrooms: 5,
      bathrooms: 4,
      area: 300,
      plotArea: 1200,
      yearBuilt: 2022,
      parking: true,
      elevator: true,
      balcony: true,
      garden: true,
      cellar: true,
      energyClass: 'A+',
    },
    amenities: ['Infinitypool', 'Bootssteg', 'Smart Home', 'Weinkeller', 'Heimkino', 'Wellnessbereich', 'Doppelgarage'],
    images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=500&fit=crop',
      'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&h=500&fit=crop',
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=500&fit=crop',
    ],
    vrTours: [
      {
        id: 'vr-4-1',
        panoramaUrl: PANORAMA_URLS.livingroom,
        thumbnailUrl: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=120&h=80&fit=crop',
        roomName: 'Great Room',
        roomNameDe: 'Wohnhalle',
      },
      {
        id: 'vr-4-2',
        panoramaUrl: PANORAMA_URLS.bedroom,
        thumbnailUrl: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=120&h=80&fit=crop',
        roomName: 'Master Bedroom',
        roomNameDe: 'Hauptschlafzimmer',
      },
      {
        id: 'vr-4-3',
        panoramaUrl: PANORAMA_URLS.exterior,
        thumbnailUrl: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=120&h=80&fit=crop',
        roomName: 'Pool Terrace',
        roomNameDe: 'Poolterrasse',
      },
    ],
    agent: agents[3],
    status: 'active',
    createdAt: '2025-01-10',
    updatedAt: '2025-02-05',
    views: 3421,
    vrViews: 2890,
    featured: true,
  },
  {
    id: 'prop-5',
    title: 'Stadtapartment München – Maxvorstadt',
    titleDe: 'Stadtapartment München – Maxvorstadt',
    description: 'Stylish apartment in Munich\'s vibrant Maxvorstadt district, surrounded by galleries, the Pinakothek museums and the English Garden. Modern interior with smart home features.',
    descriptionDe: 'Stilvolles Apartment im pulsierenden Münchner Maxvorstadt, umgeben von Galerien, den Pinakotheken und dem Englischen Garten. Modernes Interieur mit Smart-Home-Funktionen.',
    type: 'apartment',
    listingType: 'rent',
    price: 2_800,
    currency: 'EUR',
    address: {
      street: 'Türkenstraße 55',
      city: 'München',
      region: 'Bayern',
      country: 'DE',
      postalCode: '80799',
      lat: 48.1511,
      lng: 11.5747,
    },
    features: {
      rooms: 3,
      bedrooms: 2,
      bathrooms: 1,
      area: 85,
      floor: 3,
      totalFloors: 5,
      yearBuilt: 2020,
      parking: true,
      elevator: true,
      balcony: true,
      garden: false,
      cellar: true,
      energyClass: 'A',
    },
    amenities: ['Einbauküche', 'Parkettboden', 'Klimaanlage', 'Tiefgarage'],
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=500&fit=crop',
      'https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?w=800&h=500&fit=crop',
      'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800&h=500&fit=crop',
    ],
    vrTours: [
      {
        id: 'vr-5-1',
        panoramaUrl: PANORAMA_URLS.livingroom,
        thumbnailUrl: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=120&h=80&fit=crop',
        roomName: 'Living Area',
        roomNameDe: 'Wohnbereich',
      },
    ],
    agent: agents[2],
    status: 'active',
    createdAt: '2025-02-05',
    updatedAt: '2025-02-12',
    views: 672,
    vrViews: 498,
    featured: false,
  },
  {
    id: 'prop-6',
    title: 'Historisches Salzburger Stadthaus',
    titleDe: 'Historisches Salzburger Stadthaus',
    description: 'A rare gem in the Salzburg old town (UNESCO World Heritage Site). This beautifully restored townhouse offers grand rooms, original historic details and modern renovation.',
    descriptionDe: 'Ein seltenes Juwel in der Salzburger Altstadt (UNESCO Weltkulturerbe). Dieses wunderschön restaurierte Stadthaus bietet repräsentative Räume, originale Historik und moderne Sanierung.',
    type: 'house',
    listingType: 'sale',
    price: 3_200_000,
    currency: 'EUR',
    pricePerSqm: 9_412,
    address: {
      street: 'Getreidegasse 22',
      city: 'Salzburg',
      region: 'Salzburg',
      country: 'AT',
      postalCode: '5020',
      lat: 47.7999,
      lng: 13.0433,
    },
    features: {
      rooms: 10,
      bedrooms: 5,
      bathrooms: 3,
      area: 340,
      plotArea: 250,
      yearBuilt: 1780,
      parking: false,
      elevator: true,
      balcony: true,
      garden: true,
      cellar: true,
      energyClass: 'C',
    },
    amenities: ['Historischer Keller', 'Innenhof', 'Fresco-Decken', 'Gewölbe', 'Dachterrasse'],
    images: [
      'https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=800&h=500&fit=crop',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=500&fit=crop',
      'https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?w=800&h=500&fit=crop',
    ],
    vrTours: [
      {
        id: 'vr-6-1',
        panoramaUrl: PANORAMA_URLS.livingroom,
        thumbnailUrl: 'https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=120&h=80&fit=crop',
        roomName: 'Grand Salon',
        roomNameDe: 'Großer Salon',
      },
      {
        id: 'vr-6-2',
        panoramaUrl: PANORAMA_URLS.exterior,
        thumbnailUrl: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=120&h=80&fit=crop',
        roomName: 'Courtyard',
        roomNameDe: 'Innenhof',
      },
    ],
    agent: agents[1],
    status: 'active',
    createdAt: '2024-12-15',
    updatedAt: '2025-01-20',
    views: 1876,
    vrViews: 1432,
    featured: true,
  },
  {
    id: 'prop-7',
    title: 'Bergchalet Zermatt mit Matterhorn-Blick',
    titleDe: 'Bergchalet Zermatt mit Matterhorn-Blick',
    description: 'Exclusive alpine chalet in Zermatt with direct, unobstructed views of the iconic Matterhorn. Ski-in/ski-out, private spa, and the highest standard of Swiss craftsmanship.',
    descriptionDe: 'Exklusives Bergchalet in Zermatt mit direktem Blick auf das Matterhorn. Ski-in/Ski-out, privater Spa-Bereich und höchste Schweizer Handwerkskunst.',
    type: 'chalet',
    listingType: 'sale',
    price: 6_500_000,
    currency: 'CHF',
    pricePerSqm: 18_056,
    address: {
      street: 'Riedweg 15',
      city: 'Zermatt',
      region: 'Wallis',
      country: 'CH',
      postalCode: '3920',
      lat: 46.0207,
      lng: 7.7491,
    },
    features: {
      rooms: 8,
      bedrooms: 5,
      bathrooms: 4,
      area: 360,
      plotArea: 600,
      yearBuilt: 2023,
      parking: false,
      elevator: true,
      balcony: true,
      garden: false,
      cellar: true,
      energyClass: 'A+',
    },
    amenities: ['Matterhorn-Panorama', 'Private Spa', 'Skiraum', 'Butler-Service', 'Kamin', 'Tiefkühlung', 'Weinkeller'],
    images: [
      'https://images.unsplash.com/photo-1543722530-d2c3201371e7?w=800&h=500&fit=crop',
      'https://images.unsplash.com/photo-1548504773-429e84f586d2?w=800&h=500&fit=crop',
      'https://images.unsplash.com/photo-1551882547-ff40c63fe2fa?w=800&h=500&fit=crop',
    ],
    vrTours: [
      {
        id: 'vr-7-1',
        panoramaUrl: PANORAMA_URLS.livingroom,
        thumbnailUrl: 'https://images.unsplash.com/photo-1548504773-429e84f586d2?w=120&h=80&fit=crop',
        roomName: 'Alpine Lounge',
        roomNameDe: 'Alpenstube',
      },
      {
        id: 'vr-7-2',
        panoramaUrl: PANORAMA_URLS.bedroom,
        thumbnailUrl: 'https://images.unsplash.com/photo-1551882547-ff40c63fe2fa?w=120&h=80&fit=crop',
        roomName: 'Master Bedroom',
        roomNameDe: 'Schlafzimmer',
      },
      {
        id: 'vr-7-3',
        panoramaUrl: PANORAMA_URLS.exterior,
        thumbnailUrl: 'https://images.unsplash.com/photo-1543722530-d2c3201371e7?w=120&h=80&fit=crop',
        roomName: 'Mountain View Terrace',
        roomNameDe: 'Bergterrasse',
      },
    ],
    agent: agents[3],
    status: 'reserved',
    createdAt: '2025-01-05',
    updatedAt: '2025-02-15',
    views: 4120,
    vrViews: 3650,
    featured: true,
  },
  {
    id: 'prop-8',
    title: 'Designerwohnung Bregenz am Bodensee',
    titleDe: 'Designerwohnung Bregenz am Bodensee',
    description: 'Contemporary designer apartment in Bregenz with stunning views of Lake Constance. Open plan living, top-quality finishes, and a large southwest-facing terrace.',
    descriptionDe: 'Zeitgenössische Designerwohnung in Bregenz mit atemberaubendem Blick auf den Bodensee. Offener Wohnbereich, hochwertige Ausstattung und große Südwestterrasse.',
    type: 'apartment',
    listingType: 'sale',
    price: 780_000,
    currency: 'EUR',
    pricePerSqm: 8_667,
    address: {
      street: 'Seepromenade 8',
      city: 'Bregenz',
      region: 'Vorarlberg',
      country: 'AT',
      postalCode: '6900',
      lat: 47.5031,
      lng: 9.7471,
    },
    features: {
      rooms: 4,
      bedrooms: 2,
      bathrooms: 2,
      area: 90,
      floor: 5,
      totalFloors: 7,
      yearBuilt: 2022,
      parking: true,
      elevator: true,
      balcony: true,
      garden: false,
      cellar: true,
      energyClass: 'A',
    },
    amenities: ['Bodenseeblick', 'Designerküche', 'Fußbodenheizung', 'Smart Home', 'Elektroladepunkt'],
    images: [
      'https://images.unsplash.com/photo-1600607688969-a5bfcd646154?w=800&h=500&fit=crop',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=500&fit=crop',
      'https://images.unsplash.com/photo-1600210492493-0946911123ea?w=800&h=500&fit=crop',
    ],
    vrTours: [
      {
        id: 'vr-8-1',
        panoramaUrl: PANORAMA_URLS.livingroom,
        thumbnailUrl: 'https://images.unsplash.com/photo-1600607688969-a5bfcd646154?w=120&h=80&fit=crop',
        roomName: 'Open Living',
        roomNameDe: 'Wohn-Essbereich',
      },
    ],
    agent: agents[0],
    status: 'active',
    createdAt: '2025-02-10',
    updatedAt: '2025-02-18',
    views: 534,
    vrViews: 401,
    featured: false,
  },
];

export const testimonials: Testimonial[] = [
  {
    id: 'test-1',
    name: 'Andreas Kirchner',
    role: 'buyer',
    location: 'Hamburg → Innsbruck',
    text: 'I was relocating from Hamburg to Innsbruck and could not visit every property in person. Through Vistera, I virtually toured 12 apartments and narrowed it down to 2 before ever getting on a plane. Saved me at least 3 trips!',
    textDe: 'Ich zog von Hamburg nach Innsbruck um und konnte nicht jede Wohnung persönlich besichtigen. Über Vistera habe ich 12 Wohnungen virtuell besichtigt und auf 2 eingegrenzt, bevor ich überhaupt ins Flugzeug stieg. Mindestens 3 Reisen gespart!',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=60&h=60&fit=crop&crop=face',
    rating: 5,
  },
  {
    id: 'test-2',
    name: 'Maria Steinlechner',
    role: 'seller',
    location: 'Kitzbühel, Österreich',
    text: 'Als Verkäuferin wollte ich Interessenten anziehen, ohne mein Haus mit unzähligen Besichtigungen zu überfluten. Die VR-Tour hat genau das erreicht – wir hatten nur 4 echte Besichtigungen und haben dann verkauft!',
    textDe: 'Als Verkäuferin wollte ich Interessenten anziehen, ohne mein Haus mit unzähligen Besichtigungen zu überfluten. Die VR-Tour hat genau das erreicht – wir hatten nur 4 echte Besichtigungen und haben dann verkauft!',
    avatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b2e5?w=60&h=60&fit=crop&crop=face',
    rating: 5,
  },
  {
    id: 'test-3',
    name: 'Thomas Braun',
    role: 'agent',
    location: 'München, Deutschland',
    text: 'Vistera hat mein Geschäft transformiert. Ich schließe jetzt 40% mehr Deals ab, weil Käufer viel besser vorbereitet zur Besichtigung kommen. Die Qualität der Interessenten ist deutlich gestiegen.',
    textDe: 'Vistera hat mein Geschäft transformiert. Ich schließe jetzt 40% mehr Deals ab, weil Käufer viel besser vorbereitet zur Besichtigung kommen. Die Qualität der Interessenten ist deutlich gestiegen.',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=60&h=60&fit=crop&crop=face',
    rating: 5,
  },
  {
    id: 'test-4',
    name: 'Claudia Meier',
    role: 'buyer',
    location: 'Zürich, Schweiz',
    text: 'Die VR-Tour des Hauses am Zürichsee hat mir ermöglicht, es mit meiner Familie in New York zu "besuchen", bevor wir geflogen sind. Wir haben es beim ersten echten Besuch gekauft!',
    textDe: 'Die VR-Tour des Hauses am Zürichsee hat mir ermöglicht, es mit meiner Familie in New York zu "besuchen", bevor wir geflogen sind. Wir haben es beim ersten echten Besuch gekauft!',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=60&h=60&fit=crop&crop=face',
    rating: 5,
  },
];

export const stats = {
  properties: '2.400+',
  cities: '180+',
  agents: '350+',
  vrTours: '1.800+',
};
